---
title: "Problem 1"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r problem1_setup, include=FALSE}
library(tidyverse)
library(plotly)
library(readr)
library(stringr)
library(ggplot2)
library(flexdashboard)
library(forcats)
library(janitor)

# Reading in the data
nyc_inspections = read_csv("./DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz", 
                           col_types = cols(building = col_character()),
                           na = c("NA", "N/A"))
# Cleaning the data for analysis
nyc_inspections =
  nyc_inspections %>%
  clean_names() %>%
  mutate(cuisine_description = ifelse(cuisine_description == "Café/Coffee/Tea", "Cafe/Coffee/Tea", cuisine_description)) %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro)) %>%
  filter(inspection_date > "2000-01-01 UTC") %>%
  select(-action, -phone)

```

### Boxplots of Inspection Score by Cuisine

```{r boxplot}

# Identifying top 10 cuisine types
cuisine_list = nyc_inspections %>% 
  count(cuisine_description, sort = TRUE) %>% 
  top_n(10) %>% 
  select(cuisine_description)

# Merging the data back in and creating boxplot
inner_join(nyc_inspections, cuisine_list,
             by = "cuisine_description") %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>% 
  plot_ly(y = ~score, color = ~cuisine_description, type = "box",
          colors = "Set2")
```

### Donut Chart of B-Grades by Cuisine

```{r donut_chart}

# Merging the cuisine data back in and creating a donut chart
inner_join(nyc_inspections, cuisine_list,
             by = "cuisine_description") %>%
  select(cuisine_description, grade) %>%
  count(cuisine_description, grade) %>%
  filter(grade == "B") %>%
  plot_ly(labels = ~cuisine_description, values = ~n, type = "pie", hole = 0.6,
          colors = "Set2")
```

### Bar Graph of Inspection Grades by Borough

```{r bar_graph}

# Creating ggplot of the critical flags that restaurants have received
grade_bar = nyc_inspections %>%
  ggplot(aes(x = grade, fill = critical_flag)) +
  geom_bar() +
  facet_grid(. ~ boro) +
  xlab("Grade") + ylab("Number of Restaurants") +
  labs(x = "", fill = "Infraction Type")

# Converting ggplot to plotly format
ggplotly(grade_bar)
```