---
title: "Homework 6"
author: "Katie Blitsman (kb2908)"
date: "November 17, 2017"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
#Problem 1

```{r problem1_setup, include=FALSE}
library(tidyverse)
library(plotly)
library(readr)
library(stringr)
library(ggplot2)
library(flexdashboard)
library(forcats)
library(janitor)
library(shiny)

nyc_inspections = read_csv("./DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz", 
                           col_types = cols(building = col_character()),
                           na = c("NA", "N/A"))
nyc_inspections =
  nyc_inspections %>%
  clean_names() %>%
  mutate(cuisine_description = ifelse(cuisine_description == "Café/Coffee/Tea", "Cafe/coffee/Tea", cuisine_description)) %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro),
         cuisine_description) %>% 
  select(-action, -phone)

```

Column {data-width=400}
-----------------------------------------------------------------------

### Boxplots of Inspection Score by Cuisine

```{r}
cuisine_list = nyc_inspections %>% 
  count(cuisine_description, sort = TRUE) %>% 
  top_n(10) %>% 
  select(cuisine_description)

inner_join(nyc_inspections, cuisine_list,
             by = "cuisine_description") %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>% 
  plot_ly(y = ~score, color = ~cuisine_description, type = "box",
          colors = "Set2")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Donut Chart of B-Grades by Cuisine

```{r}
inner_join(nyc_inspections, cuisine_list,
             by = "cuisine_description") %>%
  select(cuisine_description, grade) %>%
  count(cuisine_description, grade) %>%
  filter(grade == "B") %>%
  plot_ly(labels = ~cuisine_description, values = ~n, type = "pie", hole = 0.6,
          colors = "Set2")
```

### Bar Graph of Inspection Grades by Borough

```{r}
grade_bar = nyc_inspections %>%
  ggplot(aes(x = grade, fill = critical_flag)) +
  geom_bar() +
  facet_grid(. ~ boro) +
  xlab("Grade") + ylab("Number of Restaurants")

ggplotly(grade_bar)
```