---
title: "Problem 2"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
runtime: shiny
---

```{r prob2_setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(readr)
library(stringr)
library(ggplot2)
library(flexdashboard)
library(forcats)
library(janitor)
library(shiny)

nyc_inspections = read_csv("./nyc_inspections.csv")

cuisine_list = read_csv("./cuisine_list.csv")
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r input_widget, echo=FALSE}
grade = nyc_inspections %>% distinct(grade) %>% pull()
first_date = min(nyc_inspections$inspection_date)
last_date = max(nyc_inspections$inspection_date)

#selectInput widget
selectInput("grade_choice", label = h3("Select grade"),
            choices = grade, selected = "A")

# sliderInput widget
sliderInput("inspection_range", label = h3("Choose inspection date range"), min = first_date, max = last_date, value = c(as.POSIXct("2012-05-01"), as.POSIXct("2017-10-17")))

```


Row
-----------------------------------------------------------------------

### Boxplots

```{r boxplot}
renderPlotly({

inner_join(nyc_inspections, cuisine_list,
             by = "cuisine_description") %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>% 
  filter(inspection_date %in% input$inspection_range[1]:input$inspection_range[2], 
         grade == input$grade_choice) %>% 
  plot_ly(y = ~score, color = ~cuisine_description, type = "box",
          colors = "Set2")
})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Donut Chart

```{r donut_chart}
renderPlotly({

  inner_join(nyc_inspections, cuisine_list,
             by = "cuisine_description") %>%
  filter(inspection_date %in% input$inspection_range[1]:input$inspection_range[2],          grade == input$grade_choice) %>% 
  select(cuisine_description, grade) %>%
  count(cuisine_description, grade) %>%
  plot_ly(labels = ~cuisine_description, values = ~n, type = "pie", hole = 0.6,
          colors = "Set2")
})
```

### Bar Graph

```{r bar_chart}
renderPlotly({
  
  grade_bar = nyc_inspections %>%
  filter(inspection_date %in% input$inspection_range[1]:input$inspection_range[2],          grade == input$grade_choice) %>% 
  ggplot(aes(x = grade, fill = critical_flag)) +
  geom_bar() +
  facet_grid(. ~ boro) +
  xlab("Grade") + ylab("Number of Restaurants")

ggplotly(grade_bar)
})

```

